name: sasl
description: "Sign Language Learning App"
version: 1.0.0
environment:
  sdk: ^3.10.7
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1
  path_provider: ^2.1.5
  audioplayers: ^6.1.0
  hive_flutter: ^1.1.0
  camera: ^0.11.3
  hive: ^2.2.3
flutter:
  uses-material-design: true
  assets:
    - assets/models/
    - assets/sounds/
    - assets/images/signs/
    - assets/data.jpg